export const fullSiteName = "Find Good Coffee"
export const siteName = "FindGoodCoffee"
export const domain = "findgood.coffee"
export const fullDomain = "https://findgood.coffee/"
export const description = "Helping coffee enthusiasts and cafe goers find the best cafes near them"
